In [1]:
%pip install -q pandas openpyxl pyarrow

Note: you may need to restart the kernel to use updated packages.

In [2]:
import os
import pandas as pd

In [3]:
df_csv = pd.read_csv("titanic.csv")

In [4]:
type(df_csv)

pandas.DataFrame

In [5]:
df_csv.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [6]:
df_csv.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [7]:
df_csv_subset =pd.read_csv(
    filepath_or_buffer = "titanic.csv",
    usecols=["PassengerId","Survived","SibSp","Name"]
)

In [8]:
df_csv_subset.head()

,PassengerId,Survived,Name,SibSp
0,1,0,"Braund, Mr. Owen Harris",1
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1
2,3,1,"Heikkinen, Miss. Laina",0
3,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1
4,5,0,"Allen, Mr. William Henry",0

In [9]:
df_csv.shape

(891, 12)

In [10]:
df_csv_subset.shape

(891, 4)

In [11]:
# loading first n rows of a csv file
df_csv_preview = pd.read_csv("titanic.csv", nrows=5)

In [12]:
df_csv_preview.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.0500,NaN,S

In [13]:
df_excel = pd.read_excel("titanic1.xlsx")

In [14]:
df_excel.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [15]:
df_xlsx_subset =pd.read_excel(
    io = "titanic1.xlsx",
    usecols=["PassengerId","Survived","SibSp"]
)

In [16]:
df_xlsx_subset.head()

   PassengerId  Survived  SibSp
0            1         0      1
1            2         1      1
2            3         1      0
3            4         1      1
4            5         0      0

In [17]:
xls=pd.ExcelFile("titanic1.xlsx")
print(xls.sheet_names)

['titanic1']

**Parquet file**

In [18]:
%pip install pyarrow

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pyarrow in C:\Users\NISMITHA\AppData\Roaming\Python\Python314\site-packages (23.0.1)
Note: you may need to restart the kernel to use updated packages.

In [19]:
import pandas as pd

In [20]:
df = pd.read_parquet(r"C:\Users\NISMITHA\Downloads\archive (2)\train.parquet")

In [21]:
df.head()

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,Family_Size,Alone
0,0,3,male,22.0,1,0,7.2500,S,1,0
1,1,1,female,38.0,1,0,71.2833,C,1,0
2,1,3,female,26.0,0,0,7.9250,S,0,1
3,1,1,female,35.0,1,0,53.1000,S,1,0
4,0,3,male,35.0,0,0,8.0500,S,0,1

In [22]:
df.shape

(891, 10)

In [23]:
df.columns

Index(['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare',
       'Embarked', 'Family_Size', 'Alone'],
      dtype='str')

**Load csv file with diff separator**

In [24]:
df_tab = pd.read_csv("titanic_tab.csv", sep="\t")
df_tab.shape

(891, 12)

In [27]:
def file_size(path):
    size_bytes = os.path.getsize(path)
    size_kb = round(size_bytes / 1024,2)
    size_mb = round(size_bytes/ (1024*1024), 4 )
    return size_kb, size_mb

for f in ["titanic.csv", "titanic1.xlsx", "train.parquet", "titanic_tab.csv"]:
    kb, mb = file_size(f)
    print(f"{f}: {kb} KB | {mb} MB")

titanic.csv: 59.76 KB | 0.0584 MB
titanic1.xlsx: 73.75 KB | 0.072 MB
train.parquet: 7.82 KB | 0.0076 MB
titanic_tab.csv: 58.91 KB | 0.0575 MB